apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  application.properties: |
    spring.application.name=recipe_app
    server.port=8080
    spring.datasource.url=jdbc:mysql://mysql-service:3306/recipe_app
    spring.datasource.username=root
    spring.datasource.password=root
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect